import pandas as pd
import sys
import os
from datetime import datetime, timedelta

# 1. Calculate Yesterday's Date
yesterday = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')

# Check if user provided a specific date argument (e.g. python3 convert_picks.py 2026-02-10)
if len(sys.argv) > 1:
    target_date = sys.argv[1]
else:
    target_date = yesterday

filename = f"picks_{target_date}.txt"

print(f"Looking for file: {filename}...")

if not os.path.exists(filename):
    print(f"ERROR: Could not find {filename}.")
    print("This script requires the text output file generated by run_daily.sh.")
    sys.exit()

# 2. Parse the File
data = []
with open(filename, 'r') as f:
    lines = f.readlines()

for line in lines:
    # Skip headers and separator lines
    if "|" not in line or "MATCHUP" in line or "=====" in line:
        continue
    
    # Split by pipe '|' and clean whitespace
    parts = [p.strip() for p in line.split('|')]
    
    # Ensure it's a valid data row (should have 11 columns)
    if len(parts) < 11: continue

    entry = {
        'Matchup': parts[0],
        'Proj_Score': parts[1],
        'XGB_Spread': parts[2],
        'Sim_Margin': parts[3],
        'Consensus_Spread': parts[4],
        'Vegas_Line': parts[5],
        'Recommended_Pick': parts[6],
        'Edge': parts[7],
        'Confidence': parts[8],
        'Total_Pick': parts[9],
        'Analysis': parts[10]
    }
    data.append(entry)

# 3. Save to CSV
if not data:
    print("Found the file, but couldn't parse any lines. Check the format.")
else:
    df = pd.DataFrame(data)
    csv_filename = f"report_{target_date}.csv"
    df.to_csv(csv_filename, index=False)
    print(f"\nSUCCESS! 🚀")
    print(f"Converted {len(data)} picks to: {csv_filename}")
